@startuml

abstract class Vehiculo {
    - matricula: String
    - marca: String
    - modelo: String
    - añoFabricacion: int
    - kilometraje: int
    - precio: double
    - estado: Estado
    - propietario: Persona

     + calcularRiesgo(): String
     + imprimirDatos(): void
}

abstract class Coche extends Vehiculo {
        - numPuertas: int
        - tipoCombustible: Combustible
        - capacidadMaletero: int
        - traccion: Traccion
}

class Sedan {
    - espacioInterior: double
    - nivelConfort: Confort
}

class Suv {
    - capacidadOffroad: boolean
    - alturaLibreSuelo: double
}

class Deportivo {
    - aceleracion0a100: double
    - potenciaCV: int
    - tieneModoPista: boolean
}

abstract class Moto extends Vehiculo{
    - cilindrada: int
    - peso: int
    - alturaAsiento: double
    - tipoTransmision: Transmision
}

class Scooter {
    - espacioBajoAsiento: int
}

class MotoDeportiva {
    - velocidadMaxima: double
    - tieneQuickShifter: boolean
}

class Camion extends Vehiculo {
    - capacidadCarga: double
    - numEjes: int
    - longitudRemolque: double
    - potenciaMotor: int
}

class Persona {
    - nombreApellidos: String
    - dni: String
    - fechaCaducidadCarnet: Date
    - añoNacimiento: int
}

interface Valorable {
    + calcularDepreciacion(): double
}

Vehiculo --> Persona
Vehiculo ..|> Valorable

Coche <|-- Sedan
Coche <|-- Suv
Coche <|-- Deportivo

Moto <|-- Scooter
Moto <|-- MotoDeportiva

@enduml